version: "3.7"

services:
  trilium:
    image: zadam/trilium:latest
    restart: unless-stopped
    ports:
      - '9111:8080'
    container_name: trilium
    networks:
      - nginxproxymanager
networks:
  nginxproxymanager:
    name: nginxproxymanager
    external: true
