version: "3.7"

services:
  openproject:
    image: openproject/community:12
    restart: unless-stopped
    ports:
      - '2082:8080'
    environment:
      OPENPROJECT_SECRET_KEY_BASE: 'U8d@x%uUAPQCNh$$1mEP*KQ2'
      OPENPROJECT_HOST__NAME: 'openproject:9113'
      OPENPROJECT_HTTPS: 'false'
    container_name: openproject
    networks:
      - nginxproxymanager
networks:
  nginxproxymanager:
    name: nginxproxymanager
    external: true
